openapi: 3.0.0
info:
  title: Open Maneki API
  version: '1.0'
  description: 株式資産管理アプリケーションのAPI仕様

servers:
  - url: http://localhost:5173/api/v1

tags:
  - name: stock
    description: 保有証券情報を管理する
  - name: dividend
    description: 配当情報を管理する

paths:
  /dividend:
    put:
      tags:
        - dividend
      summary: 配当情報の追加/更新
      description: 指定された銘柄の配当情報を追加あるいは重複する情報がある場合は更新します
      operationId: insertDividend
      requestBody:
        description: 登録したい配当情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DividendInsertRequest'
      responses:
        '200':
          description: 登録/更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DividendInsertResponse'
        '400':
          description: バリデーションエラー
        '500':
          description: サーバーエラー

components:
  schemas:
    DividendInsertRequest:
      type: object
      required:
        - market
        - code
        - name
        - amount
        - recordDate
      properties:
        market:
          type: string
          description: 市場区分
          enum:
            - TSE
            - NYSE
            - NASDAQ
          example: 'TSE'
        code:
          type: string
          description: 銘柄コード
          example: '1234'
        name:
          type: string
          description: 銘柄名
          example: 'テスト株式'
        amount:
          type: number
          description: 配当金単価
          example: 100
        recordDate:
          type: string
          format: date-time
          description: 権利落ち日
          example: 2020-03-31
    DividendInsertResponse:
      type: object
